/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_KXvFehCTz",
    "aws_user_pools_web_client_id": "6pc6l4vih2n3fut9necc2lstvv",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3h5qxmqtozh6njgfu3utog5wmm.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ubfiuox4ovaz3pcqeiutow3jze"
};


export default awsmobile;